In [12]:
import sys
import os
sys.path.append(os.path.abspath('..')) # Points Python to the parent folder

from data.market_data import MarketDataFetcher
import datetime
import pandas as pd 
import numpy as np

start_date = datetime.date(2021, 1, 1)
end_date = datetime.date.today()
tickers = ["msft", "aapl"]
md = MarketDataFetcher()

df = md.fetch_multiple(tickers=tickers, start_date=start_date, end_date= end_date)

close_prices = pd.DataFrame({
    ticker: data['Close'].squeeze() 
    for ticker, data in df.items()
})


close_prices["msft"]

Date
2021-01-04    207.956146
2021-01-05    208.156738
2021-01-06    202.759369
2021-01-07    208.529266
2021-01-08    209.799820
                 ...    
2026-07-20    402.290009
2026-07-21    397.750000
2026-07-22    390.339996
2026-07-23    381.579987
2026-07-24           NaN
Name: msft, Length: 1395, dtype: float64

In [13]:
cov_matrix = close_prices.cov()
cov_matrix.iloc[0, 1]

3473.6502356901874

In [14]:
corr = close_prices.corr()
corr.iloc[0, 1]

0.8160596085567823

In [15]:
x_raw = np.array([0.01, -0.02, 0.03, 0.00, -0.01]) 
x_raw

array([ 0.01, -0.02,  0.03,  0.  , -0.01])

In [16]:
ones = np.ones(len(x_raw))
ones

array([1., 1., 1., 1., 1.])

In [17]:
stacked = np.vstack([x_raw, ones])
stacked

array([[ 0.01, -0.02,  0.03,  0.  , -0.01],
       [ 1.  ,  1.  ,  1.  ,  1.  ,  1.  ]])

In [18]:
X_final = stacked.T
X_final

array([[ 0.01,  1.  ],
       [-0.02,  1.  ],
       [ 0.03,  1.  ],
       [ 0.  ,  1.  ],
       [-0.01,  1.  ]])

In [21]:
df_benchmark = md.get_historical_prices("^SPX", start_date="2025-01-01", end_date="2026-01-01")
df_benchmark["Close"]

Ticker,^SPX
Date,
2025-01-02,5868.549805
2025-01-03,5942.470215
2025-01-06,5975.379883
2025-01-07,5909.029785
2025-01-08,5918.250000
...,...
2025-12-24,6932.049805
2025-12-26,6929.939941
2025-12-29,6905.740234
